// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/GetImageCd/GetImageCd.proto

package go_micro_service_GetImageCd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Response struct {
	Error  string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	//图片结构元素
	Pix []byte `protobuf:"bytes,3,opt,name=Pix,proto3" json:"Pix,omitempty"`
	//图片的跨度
	Stride               int64           `protobuf:"varint,4,opt,name=Stride,proto3" json:"Stride,omitempty"`
	Min                  *Response_Point `protobuf:"bytes,5,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  *Response_Point `protobuf:"bytes,6,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetPix() []byte {
	if m != nil {
		return m.Pix
	}
	return nil
}

func (m *Response) GetStride() int64 {
	if m != nil {
		return m.Stride
	}
	return 0
}

func (m *Response) GetMin() *Response_Point {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *Response) GetMax() *Response_Point {
	if m != nil {
		return m.Max
	}
	return nil
}

type Response_Point struct {
	X                    int64    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Point) Reset()         { *m = Response_Point{} }
func (m *Response_Point) String() string { return proto.CompactTextString(m) }
func (*Response_Point) ProtoMessage()    {}
func (*Response_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{2, 0}
}

func (m *Response_Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Point.Unmarshal(m, b)
}
func (m *Response_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Point.Marshal(b, m, deterministic)
}
func (m *Response_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Point.Merge(m, src)
}
func (m *Response_Point) XXX_Size() int {
	return xxx_messageInfo_Response_Point.Size(m)
}
func (m *Response_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Point proto.InternalMessageInfo

func (m *Response_Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Response_Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type SmsRequest struct {
	//手机号
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	//图片验证码的值
	Imagestr string `protobuf:"bytes,2,opt,name=imagestr,proto3" json:"imagestr,omitempty"`
	//uuid
	Uuid                 string   `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsRequest) Reset()         { *m = SmsRequest{} }
func (m *SmsRequest) String() string { return proto.CompactTextString(m) }
func (*SmsRequest) ProtoMessage()    {}
func (*SmsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{3}
}

func (m *SmsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsRequest.Unmarshal(m, b)
}
func (m *SmsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsRequest.Marshal(b, m, deterministic)
}
func (m *SmsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsRequest.Merge(m, src)
}
func (m *SmsRequest) XXX_Size() int {
	return xxx_messageInfo_SmsRequest.Size(m)
}
func (m *SmsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SmsRequest proto.InternalMessageInfo

func (m *SmsRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SmsRequest) GetImagestr() string {
	if m != nil {
		return m.Imagestr
	}
	return ""
}

func (m *SmsRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type SmsResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsResponse) Reset()         { *m = SmsResponse{} }
func (m *SmsResponse) String() string { return proto.CompactTextString(m) }
func (*SmsResponse) ProtoMessage()    {}
func (*SmsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{4}
}

func (m *SmsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsResponse.Unmarshal(m, b)
}
func (m *SmsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsResponse.Marshal(b, m, deterministic)
}
func (m *SmsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsResponse.Merge(m, src)
}
func (m *SmsResponse) XXX_Size() int {
	return xxx_messageInfo_SmsResponse.Size(m)
}
func (m *SmsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SmsResponse proto.InternalMessageInfo

func (m *SmsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SmsResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type StreamingRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{5}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{6}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{7}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{8}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type PostRetRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	SmsCode              string   `protobuf:"bytes,3,opt,name=SmsCode,proto3" json:"SmsCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostRetRequest) Reset()         { *m = PostRetRequest{} }
func (m *PostRetRequest) String() string { return proto.CompactTextString(m) }
func (*PostRetRequest) ProtoMessage()    {}
func (*PostRetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{9}
}

func (m *PostRetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRetRequest.Unmarshal(m, b)
}
func (m *PostRetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRetRequest.Marshal(b, m, deterministic)
}
func (m *PostRetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRetRequest.Merge(m, src)
}
func (m *PostRetRequest) XXX_Size() int {
	return xxx_messageInfo_PostRetRequest.Size(m)
}
func (m *PostRetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostRetRequest proto.InternalMessageInfo

func (m *PostRetRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *PostRetRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PostRetRequest) GetSmsCode() string {
	if m != nil {
		return m.SmsCode
	}
	return ""
}

type PostRetResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	SessionId            string   `protobuf:"bytes,3,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostRetResponse) Reset()         { *m = PostRetResponse{} }
func (m *PostRetResponse) String() string { return proto.CompactTextString(m) }
func (*PostRetResponse) ProtoMessage()    {}
func (*PostRetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{10}
}

func (m *PostRetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRetResponse.Unmarshal(m, b)
}
func (m *PostRetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRetResponse.Marshal(b, m, deterministic)
}
func (m *PostRetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRetResponse.Merge(m, src)
}
func (m *PostRetResponse) XXX_Size() int {
	return xxx_messageInfo_PostRetResponse.Size(m)
}
func (m *PostRetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostRetResponse proto.InternalMessageInfo

func (m *PostRetResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *PostRetResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *PostRetResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.service.GetImageCd.Message")
	proto.RegisterType((*Request)(nil), "go.micro.service.GetImageCd.Request")
	proto.RegisterType((*Response)(nil), "go.micro.service.GetImageCd.Response")
	proto.RegisterType((*Response_Point)(nil), "go.micro.service.GetImageCd.Response.Point")
	proto.RegisterType((*SmsRequest)(nil), "go.micro.service.GetImageCd.SmsRequest")
	proto.RegisterType((*SmsResponse)(nil), "go.micro.service.GetImageCd.SmsResponse")
	proto.RegisterType((*StreamingRequest)(nil), "go.micro.service.GetImageCd.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.service.GetImageCd.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "go.micro.service.GetImageCd.Ping")
	proto.RegisterType((*Pong)(nil), "go.micro.service.GetImageCd.Pong")
	proto.RegisterType((*PostRetRequest)(nil), "go.micro.service.GetImageCd.PostRetRequest")
	proto.RegisterType((*PostRetResponse)(nil), "go.micro.service.GetImageCd.PostRetResponse")
}

func init() { proto.RegisterFile("proto/GetImageCd/GetImageCd.proto", fileDescriptor_208a871f55559f63) }

var fileDescriptor_208a871f55559f63 = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x6b, 0xd4, 0x40,
	0x14, 0xed, 0x34, 0xfb, 0xd5, 0xdb, 0x45, 0xeb, 0x50, 0x4a, 0x48, 0x55, 0xb6, 0x51, 0x31, 0x52,
	0x8d, 0xa5, 0x3e, 0x8a, 0x4f, 0xa5, 0x48, 0x1f, 0x16, 0x42, 0x22, 0xd2, 0x3e, 0x54, 0x48, 0x37,
	0xd7, 0x30, 0xd4, 0x64, 0xea, 0xcc, 0xac, 0xae, 0x3f, 0xc0, 0x5f, 0xed, 0x8b, 0xcc, 0xec, 0xe4,
	0x43, 0x29, 0xd9, 0x65, 0xdf, 0xee, 0xc9, 0x3d, 0x77, 0xee, 0x9c, 0x33, 0x67, 0x17, 0x8e, 0xee,
	0x04, 0x57, 0xfc, 0xed, 0x47, 0x54, 0x17, 0x45, 0x9a, 0xe3, 0x59, 0xd6, 0x2a, 0x43, 0xd3, 0xa3,
	0x87, 0x39, 0x0f, 0x0b, 0x36, 0x13, 0x3c, 0x94, 0x28, 0x7e, 0xb0, 0x19, 0x86, 0x0d, 0xc5, 0x3f,
	0x84, 0xe1, 0x14, 0xa5, 0x4c, 0x73, 0xa4, 0x7b, 0xe0, 0xc8, 0xf4, 0x97, 0x4b, 0x26, 0x24, 0xd8,
	0x89, 0x75, 0xe9, 0x3f, 0x81, 0x61, 0x8c, 0xdf, 0xe7, 0x28, 0x15, 0xa5, 0xd0, 0x9b, 0xcf, 0x59,
	0x66, 0xbb, 0xa6, 0xf6, 0x7f, 0x6f, 0xc3, 0x28, 0x46, 0x79, 0xc7, 0x4b, 0x89, 0x74, 0x1f, 0xfa,
	0xe7, 0x42, 0x70, 0x61, 0x19, 0x4b, 0x40, 0x0f, 0x60, 0x70, 0x2e, 0x44, 0x21, 0x73, 0x77, 0xdb,
	0x7c, 0xb6, 0x48, 0xef, 0x8a, 0xd8, 0xc2, 0x75, 0x26, 0x24, 0x18, 0xc7, 0xba, 0xd4, 0xcc, 0x44,
	0x09, 0x96, 0xa1, 0xdb, 0x9b, 0x90, 0xc0, 0x89, 0x2d, 0xa2, 0x1f, 0xc0, 0x99, 0xb2, 0xd2, 0xed,
	0x4f, 0x48, 0xb0, 0x7b, 0x7a, 0x1c, 0x76, 0x68, 0x09, 0xab, 0xbb, 0x84, 0x11, 0x67, 0xa5, 0x8a,
	0xf5, 0x9c, 0x19, 0x4f, 0x17, 0xee, 0x60, 0x93, 0xf1, 0x74, 0xe1, 0x3d, 0x83, 0xbe, 0x41, 0x74,
	0x0c, 0xe4, 0xd2, 0x48, 0x73, 0x62, 0x72, 0xa9, 0xd1, 0x95, 0x51, 0xe4, 0xc4, 0xe4, 0xca, 0xff,
	0x04, 0x90, 0x14, 0xb2, 0x72, 0xea, 0x00, 0x06, 0x05, 0xbf, 0x61, 0xdf, 0xd0, 0x3a, 0x61, 0x11,
	0xf5, 0x60, 0xc4, 0xf4, 0x26, 0xa9, 0x84, 0x35, 0xa3, 0xc6, 0xb5, 0xbb, 0x4e, 0xcb, 0xdd, 0xf7,
	0xb0, 0x6b, 0x4e, 0xdd, 0xc4, 0x5f, 0x3f, 0x80, 0xbd, 0x44, 0x09, 0x4c, 0x0b, 0x56, 0xe6, 0xd5,
	0xc5, 0xf6, 0xa1, 0x3f, 0xe3, 0xf3, 0x52, 0x59, 0x19, 0x4b, 0xe0, 0xbf, 0x82, 0x47, 0x2d, 0x66,
	0xb3, 0xec, 0x1e, 0xea, 0x53, 0xe8, 0x45, 0xac, 0xcc, 0xf5, 0x52, 0xa9, 0x04, 0xbf, 0x45, 0xdb,
	0xb6, 0xc8, 0xf4, 0x79, 0x47, 0xff, 0x0b, 0x3c, 0x88, 0xb8, 0x54, 0x31, 0xaa, 0x96, 0x57, 0xd3,
	0x7f, 0xbc, 0x9a, 0xd6, 0x5e, 0x45, 0xa9, 0x94, 0x3f, 0xb9, 0xc8, 0x2a, 0xaf, 0x2a, 0x4c, 0x5d,
	0x18, 0x26, 0x85, 0x3c, 0xe3, 0x19, 0x5a, 0xbb, 0x2a, 0xe8, 0x5f, 0xc3, 0xc3, 0xfa, 0xfc, 0x8d,
	0x52, 0xf9, 0x18, 0x76, 0x12, 0x94, 0x92, 0xf1, 0xf2, 0xa2, 0x7a, 0x8b, 0xe6, 0xc3, 0xe9, 0x1f,
	0x07, 0xa0, 0x89, 0x0b, 0xbd, 0x86, 0x71, 0x8d, 0x78, 0x86, 0xf4, 0xf9, 0x8a, 0x70, 0x19, 0xc5,
	0xde, 0x8b, 0xb5, 0x22, 0xe8, 0x6f, 0xd1, 0xd4, 0x2c, 0xb3, 0xd2, 0xe8, 0xcb, 0xce, 0xb1, 0x26,
	0x7d, 0x5e, 0xb0, 0x9a, 0x58, 0xaf, 0xb8, 0x35, 0x3f, 0x39, 0x4c, 0x0b, 0xfa, 0xa6, 0x7b, 0xea,
	0xbf, 0x24, 0x79, 0xe1, 0xba, 0xf4, 0x6a, 0xd5, 0x09, 0xa1, 0x9f, 0x61, 0xa4, 0xc3, 0x63, 0x02,
	0x72, 0xd4, 0x39, 0xaf, 0x69, 0xde, 0x0a, 0x0a, 0x2f, 0x73, 0x7f, 0x2b, 0x20, 0x27, 0x84, 0x7e,
	0x85, 0xa1, 0x7d, 0x74, 0x7a, 0xbc, 0x62, 0xa6, 0x1d, 0x3d, 0xef, 0xf5, 0x7a, 0xe4, 0x4a, 0xc1,
	0xcd, 0xc0, 0xfc, 0x99, 0xbe, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x90, 0xf8, 0x68, 0x71,
	0x05, 0x00, 0x00,
}
